---
- name: Minha primeira Playbook
  hosts: dexter
  vars:
    - pacotes:
      - vim
      - htop
  tasks:
    - name: Instala pacotes para RedHat
      yum:
        name: '{{ pacotes }}'
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Instala pacotes para Debian
      apt:
        name: '{{ pacotes }}'
        state: present
      when: ansible_os_family == 'Debian'